ember: &defaults
  image: randallmorey/ember-cli:2.4.2
  command: ['server', '--watcher', 'polling']
  volumes:
    - .:/ember-cli-app
  ports:
    - 4200:4200
    - 49152:49152
npm:
  <<: *defaults
  entrypoint: ['/usr/bin/npm']
  command: ['--help']
bower:
  <<: *defaults
  entrypoint: ['/usr/bin/bower', '--allow-root', '--config.interactive=false']
  command: ['--help']
